### ISSUE TITLE
Vereiste [DO1]: zorg voor een werkende build pipeline (CI)

### ISSUE THREAD

**Issue by arothuis-hu** [aegroot/cisq1-lingo#1]
Je gebruikt nu drie verschillende YML files en op dit moment draait je continuous integration pipeline niet!
Lees de opdracht goed door en wees kritisch of het werkt.

Zorg dat je er maar ééntje hebt (`build.yml`), met de volgende inhoud:

```yml
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B verify -Dspring.profiles.active=ci
```

Verwijder de overige `.yml` files.

Let op dat hier deelopdracht 4 nog niet in zit.
